const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";
const USER_DELETE = "USER_DELETE";
const USER_EDIT = "USER_EDIT";

export { FETCH_USERS_REQUEST, FETCH_USER_SUCCESS, FETCH_USERS_SUCCESS, FETCH_USERS_FAILURE, USER_DELETE, USER_EDIT };